parameters:
  - name: ArtifactName
  - name: Version

variables:
  - name: package_version
    value: ${{ parameters.Version }}

steps:

  - task: DotNetCoreCLI@2
    displayName: 'Pack Pre-Release Version Packages'
    inputs:
      command: pack
      packagesToPack: '**/src/*/*.csproj'
      versioningScheme: byEnvVar
      versionEnvVar: package_version
      outputDir: '$(Build.ArtifactStagingDirectory)/PackOut/'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/PackOut/'
      artifactName: ${{ parameters.ArtifactName }}
      artifactType: 'pipeline'