parameters:
- name: ArtifactName
- name: VersionEnvVar

steps:

  - task: DotNetCoreCLI@2
    displayName: 'Pack Pre-Release Version Packages'
    inputs:
      command: pack
      packagesToPack: '$(Build.SourcesDirectory)/src/**/*.csproj'
      versioningScheme: byEnvVar
      versionEnvVar: ${{ parameters.VersionEnvVar }}
      outputDir: '$(Build.ArtifactStagingDirectory)/PackOut/'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/PackOut/'
      artifactName: ${{ parameters.ArtifactName }}
      artifactType: 'pipeline'