parameters:
- name: ArtifactName
- name: Version

steps:
  - task: DotNetCoreCLI@2
    displayName: ${{ format('Pack_{0}', parameters.ArtifactName) }}
    inputs:
      command: pack
      packagesToPack: '**/src/*/*.csproj'
      versioningScheme: byEnvVar
      versionEnvVar: package_version
      outputDir: '$(Build.ArtifactStagingDirectory)/PackOut/'
    env:
      package_version: ${{ parameters.Version }}

  - task: CopyFiles@2
    inputs:
      contents: ${{ format('$(Build.ArtifactStagingDirectory)/PackOut/*{0}*', parameters.Version) }}
      targetFolder: ${{ format('$(Build.ArtifactStagingDirectory)/{0}', parameters.ArtifactName) }}

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: ${{ format('$(Build.ArtifactStagingDirectory)/{0}', parameters.ArtifactName) }}
      artifactName: ${{ parameters.ArtifactName }}
      artifactType: 'pipeline'
