parameters:
- name: ArtifactName

steps:

  - task: DotNetCoreCLI@2
    displayName: 'Pack Pre-Release Version Packages'
    inputs:
      command: pack
      packagesToPack: '$(Build.SourcesDirectory)/src/**/*.csproj'
      # Versioning is done during the build
      versioningScheme: off
      outputDir: '$(Build.ArtifactStagingDirectory)/PackOut/'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/PackOut/'
      artifactName: ${{ parameters.ArtifactName }}
      artifactType: 'pipeline'