parameters:
- name: createPreRelease
  displayName: 'Create Pre-Release Packages?'
  type: boolean
  default: false
- name: createRelease
  displayName: 'Create Release Packages?'
  type: boolean
  default: false

steps:

  - ${{ if eq(parameters.createPreRelease, true) }}:
    - task: DotNetCoreCLI@2
      displayName: 'Pack Pre-Release Version Packages'
      inputs:
        command: pack
        packagesToPack: '$(Build.SourcesDirectory)/src/**/*.csproj'
        versioningScheme: byEnvVar
        versionEnvVar: packageversion-prerelease
        outputDir: '$(Build.ArtifactStagingDirectory)/prerelease/'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/prerelease/'
        artifactName: 'prerelease-packages'
        artifactType: 'pipeline'

  - ${{ if eq(parameters.createRelease, true) }}:
    - task: DotNetCoreCLI@2
      displayName: 'Pack Release Version Packages'
      inputs:
        command: pack
        packagesToPack: '$(Build.SourcesDirectory)/src/**/*.csproj'
        versioningScheme: byEnvVar
        versionEnvVar: packageversion-release
        outputDir: '$(Build.ArtifactStagingDirectory)/release/'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/prerelease/'
        artifactName: 'release-packages'
        artifactType: 'pipeline'