parameters:
- name: ArtifactName
- name: Version

steps:
  - task: DotNetCoreCLI@2
    displayName: ${{ format('Pack_{0}', parameters.ArtifactName) }}
    inputs:
      command: pack
      packagesToPack: '**/src/*/*.csproj'
      versioningScheme: byEnvVar
      versionEnvVar: package_version
      outputDir: '$(Build.ArtifactStagingDirectory)/PackOut/'
    env:
      package_version: ${{ parameters.Version }}

  - task: CopyFiles@2
    inputs:
      contents: ${{ format('{0}/PackOut/*{1}*', variables['Build.ArtifactStagingDirectory'], parameters.Version) }}
      targetFolder: ${{ format('{0}/{1}', variables['Build.ArtifactStagingDirectory'], parameters.ArtifactName) }}

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: ${{ format('{0}/{1}', variables['Build.ArtifactStagingDirectory'], parameters.ArtifactName) }}
      artifactName: ${{ parameters.ArtifactName }}
      artifactType: 'pipeline'
