# DESCRIPTION: 	
# Builds, tests, and packages the solution for the main branch.	

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:-r)
trigger: none

resources:
  repositories:
  - repository: azure-health-data-services-toolkit-build-tools
    type: git
    name: AzureHealthDataServicesToolkit/azure-health-data-services-toolkit-build-tools

variables:
  - group: toolkit-test-pack
  - group: toolkit-build-version-configuration

stages:
  - stage: Build

    jobs:
    - job: CodeChecks
      pool:
        vmImage: $(WindowsVmImage)
      steps:
      - template: ./jobs/checkCode.yml

    - job: BuildTestPack
      pool:
        vmImage: $(VmImage)
      steps:
      - template: ./jobs/build.yml
      - template: ./jobs/pack.yml
        parameters:
          PackageArtifactName: ReleasePackages
          MajorVersion: $(ahds-toolkit-release-major)
          MinorVersion: $(ahds-toolkit-release-minor)
          PatchVersion: $(ahds-toolkit-release-patch)
          RevisionVersion: $(ahds-toolkit-release-revision)
      - ${{if and(in(variables['Build.Reason'], 'Manual', ''), eq(variables['System.TeamProject'], 'AzureHealthDataServicesToolkit'))}}:
        - template: ./jobs/pack.yml
          parameters:
            PackageArtifactName: PrereleasePackages
            MajorVersion: $(ahds-toolkit-prerelease-major)
            MinorVersion: $(ahds-toolkit-prerelease-minor)
            PatchVersion: $(ahds-toolkit-prerelease-patch)
            RevisionVersion: $(ahds-toolkit-prerelease-revision)

    # Run release only on manual build (Build.Reason is sometimes blank here) against the internal project. Run for both release and pre-release
  - ${{if and(in(variables['Build.Reason'], 'Manual', ''), eq(variables['System.TeamProject'], 'AzureHealthDataServicesToolkit'))}}:
    - template: ./stages/release.yml
      parameters:
        PackageArtifactName: PrereleasePackages
        GithubReleseTag: $(packageversion-prerelease)
        DevOpsFeedID: AzureHealthDataServicesToolkit/AzureHealthDataServicesToolkitInternal
        IsPrerelease: true

    - template: ./stages/release.yml
      parameters:
        PackageArtifactName: ReleasePackages
        GithubReleseTag: $(packageversion-release)
        DevOpsFeedID: AzureHealthDataServicesToolkit/AzureHealthDataServicesToolkitInternal
        IsPrerelease: false