# DESCRIPTION: 	
# Builds, tests, and packages the solution for the main branch.	

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:-r)
trigger: none

resources:
  repositories:
  - repository: azure-health-data-services-toolkit-build-tools
    type: git
    name: AzureHealthDataServicesToolkit/azure-health-data-services-toolkit-build-tools

variables:
  - group: toolkit-test-pack
  - group: toolkit-build-version-configuration

  - name: packageversion-prerelease
    ${{ if eq(variables.ahds-toolkit-prerelease-revision, '') }}:
      value: $(ahds-toolkit-prerelease-major).$(ahds-toolkit-prerelease-minor).$(ahds-toolkit-prerelease-patch)-prerelease
    ${{ else }}:
      value: $(ahds-toolkit-prerelease-major).$(ahds-toolkit-prerelease-minor).$(ahds-toolkit-prerelease-patch)-prerelease.$(ahds-toolkit-prerelease-revision)
  - name: packageversion-release
    ${{ if eq(variables.ahds-toolkit-release-revision, '') }}:
      value: $(ahds-toolkit-release-major).$(ahds-toolkit-release-minor).$(ahds-toolkit-release-patch)
    ${{ else }}:
      value: $(ahds-toolkit-release-major).$(ahds-toolkit-release-minor).$(ahds-toolkit-release-patch).$(ahds-toolkit-release-revision)

stages:
  - stage: Build

    jobs:
    - job: CodeChecks
      pool:
        vmImage: $(WindowsVmImage)
      steps:
      - template: ./jobs/checkCode.yml

    - job: BuildTestPack
      pool:
        vmImage: $(VmImage)
      steps:
      - template: ./jobs/build.yml
      - template: ./jobs/pack.yml
        parameters:
          PackageArtifactName: ReleasePackages
          Version: $(packageversion-release)
          AssemblyVersion: $(ahds-toolkit-release-major).0.0.0
      - ${{if and(in(variables['Build.Reason'], 'Manual', ''), eq(variables['System.TeamProject'], 'AzureHealthDataServicesToolkit'))}}:
        - template: ./jobs/pack.yml
          parameters:
            PackageArtifactName: PrereleasePackages
            Version: $(packageversion-prerelease)
            AssemblyVersion: $(ahds-toolkit-prerelease-major).0.0.0

    # Run release only on manual build (Build.Reason is sometimes blank here) against the internal project. Run for both release and pre-release
  - ${{if and(in(variables['Build.Reason'], 'Manual', ''), eq(variables['System.TeamProject'], 'AzureHealthDataServicesToolkit'))}}:
    - template: ./stages/release.yml
      parameters:
        PackageArtifactName: PrereleasePackages
        GithubReleseTag: $(packageversion-prerelease)
        DevOpsFeedID: AzureHealthDataServicesToolkit/AzureHealthDataServicesToolkitInternal
        IsPrerelease: true

    - template: ./stages/release.yml
      parameters:
        PackageArtifactName: ReleasePackages
        GithubReleseTag: $(packageversion-release)
        DevOpsFeedID: AzureHealthDataServicesToolkit/AzureHealthDataServicesToolkitInternal
        IsPrerelease: false