trigger:
  paths:
    include: 
      - .azdo/generators/
      - samples/Quickstart
      - .azdo/pipelines/repoman.yml
  branches: 
    include:
      - main

pr:
  paths:
    include: 
      - .azdo/generators/
      - samples/Quickstart
      - .azdo/pipelines/repoman.yml

variables:
  - group: toolkit-build-version-configuration
  - name: StagingRemoteName
    value: azure-samples-staging

stages:
  - stage: Validation
    jobs:
      - job: Generate_Repos_For_PR
        condition:  >-
          and(
            succeeded(),
            or(
              eq(variables['BuildReasonOverride'], 'PullRequest'),
              and(
                eq('', variables['BuildReasonOverride']),
                eq(variables['Build.Reason'], 'PullRequest')
              )
            )
          )
        pool:
          vmImage: $(VmImage)

        steps:
          - checkout: self

          - pwsh: |
              $PRNumber = '$(System.PullRequest.PullRequestNumber)'
              if ($env:PRNUMBEROVERRIDE) {
                Write-Host "PR Number override: $($env:PRNUMBEROVERRIDE)"
                $PRNumber = "$($env:PRNUMBEROVERRIDE)"
              }
              Write-Host "##vso[task.setvariable variable=PRNumber]$PRNumber"
            displayName: Set PRNumber

          - template: /.azdo/pipelines/steps/repoman-generate.yml
            parameters:
              TargetBranchName: pr/$(PRNumber)
              RemoteName: $(StagingRemoteName)

          - pwsh: |
              $repomanContent = "No changes detected."
              $repomanOutputFile = "$([System.IO.Path]::GetTempPath())/repoman.md"
              if (Test-Path $repomanOutputFile) {
                $repomanContent = Get-Content $repomanOutputFile -Raw
              }
              $tag ='<!-- #comment-repoman-generate -->'
              $content = @"
              $tag
              ## Repoman Generation Results
              Repoman pushed changes to remotes for the following projects:
              $repomanContent
              "@
              $file = New-TemporaryFile
              Set-Content -Path $file -Value $content
              Write-Host "##vso[task.setvariable variable=CommentBodyFile]$file"
            displayName: Set Repoman Content

          - task: PowerShell@2
            displayName: Post PR comment
            inputs:
              pwsh: true
              targetType: filePath
              filePath: ./eng/scripts/Update-PRComment.ps1
              arguments: >-
                -Repo 'microsoft/azure-health-data-services-toolkit'
                -PRNumber '$(PRNumber)'
                -BodyFile '$(CommentBodyFile)'
                -Tag '<!-- #comment-repoman-generate -->'
            env:
              GH_TOKEN: $(repoman-github-pat)

      - job: Publish_Staging
        condition: >-
          and(
            succeeded(),
            or(
              in(variables['BuildReasonOverride'], 'IndividualCI', 'BatchedCI'),
              and(
                eq('', variables['BuildReasonOverride']),
                in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI')
              )
            )
          )
        pool:
          vmImage: $(VmImage)

        steps:
          - checkout: self

          - pwsh: |
              $targetBranchName = 'staging'
              if ($env:TARGETBRANCHNAMEOVERRIDE) {
                Write-Host "Target branch override $($env:TARGETBRANCHNAMEOVERRIDE)"
                $targetBranchName = $env:TARGETBRANCHNAMEOVERRIDE
              }
              Write-Host "##vso[task.setvariable variable=TargetBranchName]$targetBranchName"
            displayName: Set TargetBranchName
          - template: /.azdo/pipelines/steps/repoman-generate.yml
            parameters:
              TargetBranchName: $(TargetBranchName)
              RemoteName: $(StagingRemoteName)

  - stage: Publish_Repos
    condition: >-
      and(
        succeeded(),
        or(
          eq(variables['BuildReasonOverride'], 'Manual'),
          and(
            eq('', variables['BuildReasonOverride']),
            eq(variables['Build.Reason'], 'Manual')
          )
        )
      )
    jobs:
    - deployment: Publish_Repos
      environment: github
      pool:
          vmImage: $(VmImage)

      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self

              - pwsh: |
                  $targetBranchName = ''
                  if ($env:TARGETBRANCHNAMEOVERRIDE) {
                    Write-Host "Target branch override $($env:TARGETBRANCHNAMEOVERRIDE)"
                    $targetBranchName = $env:TARGETBRANCHNAMEOVERRIDE
                  }
                  Write-Host "##vso[task.setvariable variable=TargetBranchName]$targetBranchName"
                displayName: Set TargetBranchName
              - template: /.azdo/pipelines/steps/repoman-generate.yml
                parameters:
                  TargetBranchName: $(TargetBranchName)
                  RemoteName: azure-samples-main