### YamlMime:ManagedReference
items:
- uid: Microsoft.Health.Fhir.Proxy.Security
  commentId: N:Microsoft.Health.Fhir.Proxy.Security
  id: Microsoft.Health.Fhir.Proxy.Security
  children:
  - Microsoft.Health.Fhir.Proxy.Security.Authenticator
  langs:
  - csharp
  - vb
  name: Microsoft.Health.Fhir.Proxy.Security
  nameWithType: Microsoft.Health.Fhir.Proxy.Security
  fullName: Microsoft.Health.Fhir.Proxy.Security
  type: Namespace
  assemblies:
  - Microsoft.Health.Fhir.Proxy
references:
- uid: Microsoft.Health.Fhir.Proxy.Security.Authenticator
  commentId: T:Microsoft.Health.Fhir.Proxy.Security.Authenticator
  name: Authenticator
  nameWithType: Authenticator
  fullName: Microsoft.Health.Fhir.Proxy.Security.Authenticator
