### YamlMime:ManagedReference
items:
- uid: Microsoft.Health.Fhir.Proxy.Configuration
  commentId: N:Microsoft.Health.Fhir.Proxy.Configuration
  id: Microsoft.Health.Fhir.Proxy.Configuration
  children:
  - Microsoft.Health.Fhir.Proxy.Configuration.PipelineSettings
  - Microsoft.Health.Fhir.Proxy.Configuration.ServiceConfig
  - Microsoft.Health.Fhir.Proxy.Configuration.UriExtensions
  langs:
  - csharp
  - vb
  name: Microsoft.Health.Fhir.Proxy.Configuration
  nameWithType: Microsoft.Health.Fhir.Proxy.Configuration
  fullName: Microsoft.Health.Fhir.Proxy.Configuration
  type: Namespace
  assemblies:
  - Microsoft.Health.Fhir.Proxy
references:
- uid: Microsoft.Health.Fhir.Proxy.Configuration.PipelineSettings
  commentId: T:Microsoft.Health.Fhir.Proxy.Configuration.PipelineSettings
  parent: Microsoft.Health.Fhir.Proxy.Configuration
  name: PipelineSettings
  nameWithType: PipelineSettings
  fullName: Microsoft.Health.Fhir.Proxy.Configuration.PipelineSettings
- uid: Microsoft.Health.Fhir.Proxy.Configuration.ServiceConfig
  commentId: T:Microsoft.Health.Fhir.Proxy.Configuration.ServiceConfig
  parent: Microsoft.Health.Fhir.Proxy.Configuration
  name: ServiceConfig
  nameWithType: ServiceConfig
  fullName: Microsoft.Health.Fhir.Proxy.Configuration.ServiceConfig
- uid: Microsoft.Health.Fhir.Proxy.Configuration.UriExtensions
  commentId: T:Microsoft.Health.Fhir.Proxy.Configuration.UriExtensions
  parent: Microsoft.Health.Fhir.Proxy.Configuration
  name: UriExtensions
  nameWithType: UriExtensions
  fullName: Microsoft.Health.Fhir.Proxy.Configuration.UriExtensions
- uid: Microsoft.Health.Fhir.Proxy.Configuration
  commentId: N:Microsoft.Health.Fhir.Proxy.Configuration
  name: Microsoft.Health.Fhir.Proxy.Configuration
  nameWithType: Microsoft.Health.Fhir.Proxy.Configuration
  fullName: Microsoft.Health.Fhir.Proxy.Configuration
