# DESCRIPTION: 	
# Builds, tests, and packages the solution for the main branch.	

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:-r)
trigger: none

variables:
- template: build-variables.yml

jobs:

- job: CodeChecks
  pool:
    vmImage: $(WindowsVmImage)
  steps:
  - template: ./jobs/checkCode.yml

- job: BuildAndTest
  pool:
    vmImage: $(WindowsVmImage)
  steps:
  - template: ./jobs/build.yml
  - template: ./jobs/pack.yml
    parameters:
      createPreRelease: true
      createRelease: true
