steps:

- task: UseDotNet@2
  displayName: 'Install dotnet 6.0.x agent tools dir'
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration) --no-incremental'
    projects: '**/Microsoft.AzureHealth.DataServices.*.csproj'
  displayName: 'Build toolkit projects'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration) --no-incremental'
    projects: '**/samples/**/*.csproj'
  displayName: 'Build samples projects'